{
    "作者": "自定义",
    "站名": "DJ音乐网",
    "编码": "GBK",
    "请求头": "User-Agent$MOBILE_UA",
    "主页url": "https://www.dj.net",
    "首页": "200",
    "起始页": "1",
    "分类url": "/dj-class-{cateId}-{catePg}.html",
    "分类": "慢摇串烧$13#酒吧串烧$80#专业串烧$82#歌曲连版$5#外文单曲$17#中文单曲$84#Electro$85#House$86#Deep$87#Breakbeat$88#Club$89#EDM$90#Mashup$91#Rab$92#Funky$93#流行音乐$94",
    "分类二次截取": "",
    "分类数组": "",
    "分类标题": "",
    "分类ID": "",
    "二次截取": "",
    "数组": "<a href=\"https://www.dj.net/djplay/music&&</a>",
    "图片": "",
    "标题": "title=\"&&\"",
    "副标题": "",
    "链接": "music&&.html",
    "简介": "",
    "搜索url": "/search.php?mod=music&srchtxt={wd}&searchsubmit=yes",
    "搜索数组": "<a href=\"https://www.dj.net/djplay/music&&</a>",
    "搜索标题": "title=\"&&\"",
    "搜索图片": "",
    "搜索副标题": "",
    "搜索链接": "music&&.html",
    "直接播放": "https://www.dj.net/template/zhzh_dzmusic/ajax/?action=geturl&id={id}",
    "播放头": ""
}
