"站名": "DJ音乐网",
"主页url": "https://www.dj.net",
"编码": "GBK",
"分类url": "/dj-class-{cateId}-{catePg}.html",
"分类": "慢摇串烧$13#酒吧串烧$80#专业串烧$82#歌曲连版$5#外文单曲$17#中文单曲$84#Electro$85#House$86#Deep$87#Breakbeat$88#Club$89#EDM$90#Mashup$91#Rab$92#Funky$93#流行音乐$94",
"分类二次截取": "",
"分类数组": "",
"分类标题": "",
"分类ID": "",
"二次截取": "",
"数组": "<a href=\"https://www.dj.net/djplay/music&&</a>",
"图片": "",
"标题": "title=\"&&\"",
"副标题": "",
"链接": "music&&.html",
"简介": ""
